indent = [
  "import_declaration",
  "const_declaration",
  "var_declaration",
  "type_declaration",
  "type_spec",
  # simply block should be enough
  # "function_declaration",
  # "method_declaration",
  "composite_literal",
  "func_literal",
  "literal_value",
  "expression_case",
  "default_case",
  "type_case",
  "communication_case",
  "argument_list",
  "block",
]

outdent = [
 "case",
 "}",
 "]",
 ")"
]
